### ISSUE TITLE
Book Joining Server

### ISSUE THREAD

**Issue by MonoAdrian23** [PetteriM1/InfoBook#2]
Everytime i Join the the Server, i get a new book.
I use PowerNukkit 1.4.0.0 Alpha 2
Tested with all Nukkit And PowerNukkit Versions.

**Comment by PetteriM1** [comment]
No support is given for unofficial Nukkit versions. Reopen if you are able to reproduce this using the official version

**Comment by MonoAdrian23** [comment]
But Nukkit is bullshit
PowerNukkit is the best and No lagg Software.
I cant understand why No Update for it.
Nukkit is death boy
